In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
#Read the dataset=
df = pd.read_csv('Social_Network_Ads.csv')

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['Gender']=label.fit_transform(df['Gender'])

In [7]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

##FEATURE ENGINEERING

In [8]:
df['Age Category'] = ['iGen' if 0<age<25 else 'Millenials' if 24<age<40 else 'GenX' if 39<age<56 else 'BabyBoomers' if 55<age<74 else None \
 for age in list(df['Age'].values)]

In [9]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased Age Category
0  15624510       1   19            19000          0         iGen
1  15810944       1   35            20000          0   Millenials
2  15668575       0   26            43000          0   Millenials
3  15603246       0   27            57000          0   Millenials
4  15804002       1   19            76000          0         iGen

In [10]:
df['Age Category'].value_counts()

Millenials     195
GenX           134
iGen            43
BabyBoomers     28
Name: Age Category, dtype: int64

In [11]:
#using Income category [Inter-quartile Ranges
df['Income Category'] = pd.qcut(df['EstimatedSalary'],3,labels=['Low','Medium','High'])

In [12]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased Age Category  \
0  15624510       1   19            19000          0         iGen   
1  15810944       1   35            20000          0   Millenials   
2  15668575       0   26            43000          0   Millenials   
3  15603246       0   27            57000          0   Millenials   
4  15804002       1   19            76000          0         iGen   

  Income Category  
0             Low  
1             Low  
2             Low  
3          Medium  
4          Medium

In [13]:
df['Income Category'].value_counts()

Medium    138
Low       134
High      128
Name: Income Category, dtype: int64

In [14]:
X = df[['Gender', 'Age']]
y = df['Purchased']

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train, y_test= train_test_split (X,y,test_size=0.3,random_state=101)

# USING LOGISTIC REGRESSION

In [16]:
from sklearn.linear_model import LogisticRegression

In [19]:
logmodel = LogisticRegression()

In [20]:
logmodel.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
logpredict = logmodel.predict(X_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [24]:
print(confusion_matrix(y_test,logpredict))
print('\n')
print(classification_report(y_test,logpredict))

[[74  6]
 [11 29]]


              precision    recall  f1-score   support

           0       0.87      0.93      0.90        80
           1       0.83      0.72      0.77        40

   micro avg       0.86      0.86      0.86       120
   macro avg       0.85      0.82      0.84       120
weighted avg       0.86      0.86      0.86       120



In [26]:
print("Accuracy: ", accuracy_score(y_test,logpredict))

Accuracy:  0.8583333333333333


# USING RANDOM FOREST

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rfc = RandomForestClassifier(n_estimators=400,criterion = 'entropy')

In [37]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=400, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [38]:
rfc_pred = rfc.predict(X_test)

In [39]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[68 12]
 [10 30]]


              precision    recall  f1-score   support

           0       0.87      0.85      0.86        80
           1       0.71      0.75      0.73        40

   micro avg       0.82      0.82      0.82       120
   macro avg       0.79      0.80      0.80       120
weighted avg       0.82      0.82      0.82       120



In [40]:
print("Accuracy: ", accuracy_score(y_test,rfc_pred))

Accuracy:  0.8166666666666667


In [43]:
from xgboost import XGBClassifier

In [44]:
xgb = XGBClassifier()

In [45]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [47]:
xgb_pred = xgb.predict(X_test)

In [48]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[68 12]
 [10 30]]


              precision    recall  f1-score   support

           0       0.87      0.85      0.86        80
           1       0.71      0.75      0.73        40

   micro avg       0.82      0.82      0.82       120
   macro avg       0.79      0.80      0.80       120
weighted avg       0.82      0.82      0.82       120



In [49]:
print("Accuracy: ", accuracy_score(y_test,xgb_pred))

Accuracy:  0.8666666666666667


#### USING THE ENGINEERED FEATURE IN OUR MODEL LETS SEE IF IT INCREASE  THE MODEL SIGNIFICANTLY OR NOT

### first convert the catgorical columns to numerics

In [62]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['Age Category']=label.fit_transform(df['Age Category'])
df['Income Category']=label.fit_transform(df['Income Category'])

In [64]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased  Age Category  \
0  15624510       1   19            19000          0             3   
1  15810944       1   35            20000          0             2   
2  15668575       0   26            43000          0             2   
3  15603246       0   27            57000          0             2   
4  15804002       1   19            76000          0             3   

   Income Category  
0                1  
1                1  
2                1  
3                2  
4                2

In [63]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased',
       'Age Category', 'Income Category'],
      dtype='object')

In [73]:
X = df.drop(['User ID','Purchased'],axis=1)
y = df['Purchased']

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

### USING LOGISTIC REGRESSION 

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
logmodel = LogisticRegression()

In [77]:
logmodel.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [78]:
y_pred = logmodel.predict(X_test)

In [80]:
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')
print("Accuracy: ", accuracy_score(y_test,xgb_pred))

[[74  6]
 [ 4 36]]


              precision    recall  f1-score   support

           0       0.95      0.93      0.94        80
           1       0.86      0.90      0.88        40

   micro avg       0.92      0.92      0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



Accuracy:  0.8666666666666667


### USING RANDOM FOREST

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [90]:
rfc = RandomForestClassifier(n_estimators=400,criterion='entropy')

In [91]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=400, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [92]:
y_pred = rfc.predict(X_test)

In [93]:
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')
print("Accuracy: ", accuracy_score(y_test,xgb_pred))

[[71  9]
 [ 1 39]]


              precision    recall  f1-score   support

           0       0.99      0.89      0.93        80
           1       0.81      0.97      0.89        40

   micro avg       0.92      0.92      0.92       120
   macro avg       0.90      0.93      0.91       120
weighted avg       0.93      0.92      0.92       120



Accuracy:  0.8666666666666667


# USING XGBOOST

In [94]:
from xgboost import XGBClassifier
xgb =XGBClassifier()

In [95]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [96]:
y_pred = xgb.predict(X_test)

In [97]:
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')
print("Accuracy: ", accuracy_score(y_test,xgb_pred))

[[72  8]
 [ 1 39]]


              precision    recall  f1-score   support

           0       0.99      0.90      0.94        80
           1       0.83      0.97      0.90        40

   micro avg       0.93      0.93      0.93       120
   macro avg       0.91      0.94      0.92       120
weighted avg       0.93      0.93      0.93       120



Accuracy:  0.8666666666666667
